In [4]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd

In [5]:
#load filtered relationships

filtered_relationships=pd.read_csv(
    r"C:\Users\arsha\OneDrive\Desktop\Healthcare Retrieval using qql\Data\graph_ready_relationships.csv"
)

print(filtered_relationships.shape)

display(filtered_relationships.head())

(124, 4)

      source       target relationship  count
0       pain    infection   RELATED_TO     16
1      cough   bronchitis   RELATED_TO     14
2       pain     diabetes   RELATED_TO     10
3      cough       asthma   RELATED_TO     10
4  infection  antibiotics   TREATED_BY     10

In [20]:
valid_medical_relations={

    "dizziness":[
        "hypoglycemia",
        "blood pressure",
        "bppv",
        "benign paroxysmal positional vertigo",
        "peripheral vertigo",
        "ischemia",
        "heart rhythm",
        "anemia",
        "migraine"
    ],

    "cough":[
        "asthma",
        "bronchitis",
        "sinusitis",
        "infection",
        "cold",
        "flu",
        "covid",
        "pneumonia",
        "allergy"
    ],

    "fever":[
        "infection",
        "flu",
        "viral infection",
        "typhoid",
        "covid",
        "malaria",
        "dengue"
    ],

    "headache":[
        "migraine",
        "blood pressure",
        "stress",
        "sinusitis",
        "dehydration"
    ],

    "nausea":[
        "pregnancy",
        "food poisoning",
        "infection",
        "gastritis",
        "migraine"
    ],

    "chest pain":[
        "heart attack",
        "cardiac disease",
        "angina",
        "acid reflux"
    ]
}

In [21]:
#store validated relationships

validated_relationships=[]

In [22]:
#medical semantic filtering

for _,row in filtered_relationships.iterrows():

    source=row["source"]

    target=row["target"]

    relationship=row["relationship"]

    count=row["count"]

    if source in valid_medical_relations:

        if target in valid_medical_relations[source]:

            validated_relationships.append({

                "source":source,
                "target":target,
                "relationship":relationship,
                "count":count

            })

In [23]:
#create validated dataframe

validated_relationships_df=pd.DataFrame(
    validated_relationships
)

print(validated_relationships_df.shape)

display(
    validated_relationships_df.head(10)
)

(6, 4)

      source        target relationship  count
0      cough    bronchitis   RELATED_TO     14
1      cough        asthma   RELATED_TO     10
2      cough     sinusitis   RELATED_TO      6
3     nausea     pregnancy   RELATED_TO      6
4      fever     infection   RELATED_TO      6
5  dizziness  hypoglycemia   RELATED_TO      4

In [24]:
#check dizziness relationships

dizziness_relations=validated_relationships_df[
    validated_relationships_df["source"]=="dizziness"
]

display(dizziness_relations)

      source        target relationship  count
5  dizziness  hypoglycemia   RELATED_TO      4

In [25]:
cough_relations=validated_relationships_df[
    validated_relationships_df["source"]=="cough"
    ]
display(cough_relations)

  source      target relationship  count
0  cough  bronchitis   RELATED_TO     14
1  cough      asthma   RELATED_TO     10
2  cough   sinusitis   RELATED_TO      6

In [26]:
fever_relations=validated_relationships_df[
    validated_relationships_df["source"]=="fever"
    ]
display(fever_relations)

  source     target relationship  count
4  fever  infection   RELATED_TO      6

In [27]:
#top validated relationships

validated_relationships_df=validated_relationships_df.sort_values(
    by="count",
    ascending=False
)

display(
    validated_relationships_df.head(30)
)

      source        target relationship  count
0      cough    bronchitis   RELATED_TO     14
1      cough        asthma   RELATED_TO     10
2      cough     sinusitis   RELATED_TO      6
3     nausea     pregnancy   RELATED_TO      6
4      fever     infection   RELATED_TO      6
5  dizziness  hypoglycemia   RELATED_TO      4